import { useEffect, useMemo, useRef, useState } from 'react';
import { Archive, BookOpen, Bot, CheckCircle2, ChevronDown, ChevronRight, Columns2, File, FileImage, FilePenLine, FolderOpen, Import, Library, Menu, MessageSquare, Moon, MoreHorizontal, PanelLeftClose, PanelRightClose, Plus, RotateCw, Search, Settings, Sun, Upload, ZoomIn, ZoomOut } from 'lucide-react';
import type { AiSettings, AppState, BrandConfig, ChatGptConnectionStatus, ClaimLink, EvidenceRecord, LibraryItem } from '../shared/types';
import './account.css';

type View='library'|'actions'|'arguments'|'inbox'|'checks'|'revisions'|'settings';
type Tab={id:string;title:string;kind:'item'|'compare';itemId:string;compareId?:string};
const blank:AppState={workspace:null,items:[],evidence:[],claims:[],claimLinks:[],tasks:[],checks:[],conversations:[]};
const groups=[['Manuscripts & revisions','manuscript',FilePenLine],['Books & articles','source',BookOpen],['Archival collections','archive',Archive],['Images & photographed pages','image',FileImage],['Assessments & notes','note',File]] as const;
const defaultBrand:BrandConfig={appName:'Research Desk',accent:'#d18b47',terminology:{evidence:'Evidence',claim:'Claim',workspace:'Workspace'}};

export function App(){
  const [state,setState]=useState<AppState>(blank),[view,setView]=useState<View>('library'),[tabs,setTabs]=useState<Tab[]>([]),[active,setActive]=useState<string>(),[query,setQuery]=useState(''),[sort,setSort]=useState<'title'|'recent'>('recent');
  const [leftOpen,setLeftOpen]=useState(true),[rightOpen,setRightOpen]=useState(true),[leftWidth,setLeftWidth]=useState(280),[rightWidth,setRightWidth]=useState(340),[dark,setDark]=useState(true),[notice,setNotice]=useState(''),[brand,setBrand]=useState(defaultBrand);
  const refresh=()=>window.researchDesk.getState().then(setState).catch(e=>setNotice(e.message));
  useEffect(()=>{refresh();window.researchDesk.getBrand().then(setBrand);},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.style.setProperty('--accent',brand.accent);document.title=brand.appName;},[dark,brand]);
  const openItem=(item:LibraryItem)=>{const existing=tabs.find(t=>t.itemId===item.id&&!t.compareId);if(existing){setActive(existing.id);return;}const tab={id:crypto.randomUUID(),title:item.title,kind:'item' as const,itemId:item.id};setTabs(x=>[...x,tab]);setActive(tab.id);};
  const closeTab=(id:string)=>{const i=tabs.findIndex(x=>x.id===id);const next=tabs.filter(x=>x.id!==id);setTabs(next);if(active===id)setActive(next[Math.max(0,i-1)]?.id);};
  const doImport=async(mode:'copy'|'link',paths?:string[])=>{try{const result=await window.researchDesk.importFiles(mode,paths);if(result){await refresh();setNotice(result.duplicates.length?`${result.imported.length} imported; ${result.duplicates.length} exact duplicate${result.duplicates.length===1?'':'s'} skipped.`:`${result.imported.length} file${result.imported.length===1?'':'s'} imported.`);}}catch(e:any){setNotice(e.message);}};
  const drag=(event:React.DragEvent)=>{event.preventDefault();const paths=window.researchDesk.getDroppedPaths(Array.from(event.dataTransfer.files));if(paths.length)void doImport('copy',paths);};
  const current=tabs.find(t=>t.id===active);
  if(!state.workspace)return <Welcome appName={brand.appName} onCreate={async(name)=>{const x=await window.researchDesk.createWorkspace(name);if(x)setState(x);}} onOpen={async()=>{const x=await window.researchDesk.openWorkspace();if(x)setState(x);}} onImport={async()=>{const x=await window.researchDesk.importWorkspace();if(x)setState(x);}}/>;
  return <div className="app" onDragOver={e=>e.preventDefault()} onDrop={drag}>
    <header className="titlebar"><div className="brandmark">RD</div><button className="icon-button"><Menu size={16}/></button><span className="appname">{brand.appName}</span><span className="crumb">{state.workspace.name}</span><div className="title-actions"><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={16}/>:<Moon size={16}/>}</button><button className="icon-button" onClick={()=>setLeftOpen(!leftOpen)} aria-label="Toggle library"><PanelLeftClose size={16}/></button><button className="icon-button" onClick={()=>setRightOpen(!rightOpen)} aria-label="Toggle assistant"><PanelRightClose size={16}/></button></div></header>
    <div className="workbench" style={{gridTemplateColumns:`48px ${leftOpen?leftWidth:0}px 1fr ${rightOpen?rightWidth:0}px`,'--left':`${leftWidth}px`,'--right':`${rightWidth}px`} as any}>
      <ActivityBar view={view} setView={setView}/>
      <aside className={`sidebar left ${leftOpen?'':'hidden'}`}><div className="side-heading"><span>{view==='library'?'Explorer':label(view)}</span><button className="icon-button" onClick={()=>view==='library'&&doImport('copy')}><Plus size={16}/></button></div>{view==='library'?<LibraryPane state={state} query={query} setQuery={setQuery} sort={sort} setSort={setSort} openItem={openItem} doImport={doImport}/>:<NavView view={view} state={state} refresh={refresh} openItem={openItem}/>}</aside>
      {leftOpen&&<Resizer side="left" onMove={d=>setLeftWidth(Math.min(480,Math.max(210,leftWidth+d)))}/>} 
      <main className="center"><Tabbar tabs={tabs} active={active} setActive={setActive} close={closeTab}/>{current?<DocumentView tab={current} state={state} refresh={refresh} openCompare={(compareId)=>{const tab={id:crypto.randomUUID(),title:'Compare documents',kind:'compare' as const,itemId:current.itemId,compareId};setTabs(x=>[...x,tab]);setActive(tab.id);}}/>:<Dashboard state={state} setView={setView} doImport={doImport}/>}</main>
      {rightOpen&&<Resizer side="right" onMove={d=>setRightWidth(Math.min(520,Math.max(280,rightWidth-d)))}/>} 
      <aside className={`sidebar right ${rightOpen?'':'hidden'}`}><AssistantWithModelPicker state={state} currentItemId={current?.itemId}/></aside>
    </div>
    <footer className="status"><span>● Local workspace</span><span>{state.items.length} sources · {state.evidence.length} evidence records · {state.claims.length} claims</span><span>Offline core ready</span></footer>
    {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}</div>}
  </div>;
}

export function Welcome({appName,onCreate,onOpen,onImport}:{appName:string;onCreate:(name:string)=>void;onOpen:()=>void;onImport:()=>void}){const [name,setName]=useState('New research project');const [creating,setCreating]=useState(false);const create=()=>{if(!name.trim()||creating)return;setCreating(true);Promise.resolve(onCreate(name.trim())).finally(()=>setCreating(false));};return <div className="welcome"><div className="welcome-card"><div className="hero-mark">RD</div><p className="eyebrow">OFFLINE-FIRST RESEARCH WORKSPACE</p><h1>{appName}</h1><p className="lede">Read closely. Keep evidence connected. Know what to do next.</p><div className="workspace-name"><label htmlFor="workspace-name">Workspace name</label><input id="workspace-name" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')create();}}/><span>Next, you’ll choose where its local files should live.</span></div><div className="welcome-actions"><button className="primary" disabled={!name.trim()||creating} onClick={create}><Plus size={18}/>{creating?'Choose a folder…':'Create workspace'}</button><button onClick={onOpen}><FolderOpen size={18}/>Open workspace</button><button onClick={onImport}><Import size={18}/>Import archive</button></div><div className="privacy-note"><strong>Your research stays local by default.</strong><br/>Installing this app elsewhere does not synchronize your files. Export a portable workspace to move or back it up.</div></div></div>}

function ActivityBar({view,setView}:{view:View;setView:(x:View)=>void}){const links:[View,any,string][]=[['library',Library,'Library'],['actions',CheckCircle2,'Next three actions'],['arguments',Columns2,'Argument view'],['inbox',Archive,'Evidence inbox'],['checks',CheckCircle2,'Workflow checks'],['revisions',FilePenLine,'Revision queue']];return <nav className="activity" aria-label="Primary navigation">{links.map(([id,Icon,title])=><button key={id} className={view===id?'active':''} title={title} aria-label={title} onClick={()=>setView(id)}><Icon size={22}/></button>)}<span className="spacer"/><button className={view==='settings'?'active':''} title="Settings and connections" onClick={()=>setView('settings')}><Settings size={22}/></button></nav>}
function label(view:View){return({actions:'Next three actions',arguments:'Argument view',inbox:'Evidence inbox',checks:'Workflow checks',revisions:'Revision queue',settings:'Settings & connections',library:'Explorer'} as any)[view]}

function LibraryPane({state,query,setQuery,sort,setSort,openItem,doImport}:{state:AppState;query:string;setQuery:(x:string)=>void;sort:string;setSort:(x:any)=>void;openItem:(i:LibraryItem)=>void;doImport:(m:'copy'|'link')=>void}){const [open,setOpen]=useState<Record<string,boolean>>({manuscript:true,source:true,archive:true,image:true,note:true,evidence:true});const filtered=state.items.filter(x=>x.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):b.updatedAt.localeCompare(a.updatedAt));return <><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workspace" aria-label="Search workspace"/></div><div className="toolbar"><button onClick={()=>doImport('copy')}><Upload size={14}/>Copy files</button><button onClick={()=>doImport('link')}><FolderOpen size={14}/>Link</button><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort items"><option value="recent">Recent</option><option value="title">Title</option></select></div><div className="tree">{groups.map(([name,kind,Icon])=><div key={kind}><button className="tree-group" onClick={()=>setOpen(x=>({...x,[kind]:!x[kind]}))}>{open[kind]?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<Icon size={15}/><span>{name}</span><b>{filtered.filter(x=>x.kind===kind).length}</b></button>{open[kind]&&filtered.filter(x=>x.kind===kind).map(item=><button className={`tree-item ${item.missing?'missing':''}`} key={item.id} onDoubleClick={()=>openItem(item)} onClick={()=>openItem(item)} title={item.missing?'Missing file—relink required':item.title}><File size={14}/><span>{item.title}</span>{item.storageMode==='link'&&<em>↗</em>}</button>)}</div>)}<div><button className="tree-group" onClick={()=>setOpen(x=>({...x,evidence:!x.evidence}))}>{open.evidence?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<Archive size={15}/><span>Evidence records</span><b>{state.evidence.length}</b></button>{open.evidence&&state.evidence.map(x=><div className="tree-item static" key={x.id}><span className="dot"/><span>{x.title}</span></div>)}</div></div><div className="drop-hint">Drop files anywhere to preserve copies in this workspace</div></>}

function Tabbar({tabs,active,setActive,close}:{tabs:Tab[];active?:string;setActive:(x:string)=>void;close:(x:string)=>void}){return <div className="tabs">{tabs.map(t=><button key={t.id} className={active===t.id?'active':''} onClick={()=>setActive(t.id)}><File size={14}/><span>{t.title}</span><i onClick={e=>{e.stopPropagation();close(t.id)}}>×</i></button>)}</div>}

function Dashboard({state,setView,doImport}:{state:AppState;setView:(v:View)=>void;doImport:(m:'copy'|'link')=>void}){return <div className="dashboard"><p className="eyebrow">{state.workspace?.name}</p><h1>Your research, in view.</h1><p className="lede">Sources remain original. Analytical records remain traceable. The next move stays concrete.</p><div className="metric-row"><Metric n={state.items.length} text="Sources"/><Metric n={state.evidence.length} text="Evidence records"/><Metric n={state.claims.length} text="Claims"/><Metric n={state.checks.length} text="Checks"/></div><section><div className="section-title"><h2>Next three actions</h2><button onClick={()=>setView('actions')}>Open queue →</button></div>{state.tasks.filter(x=>x.status!=='done').slice(0,3).map((t,i)=><div className="action-row" key={t.id}><b>0{i+1}</b><div><strong>{t.title}</strong><p>{t.why||'Add why this action matters.'}</p></div><span className={`tag ${t.status}`}>{t.status}</span></div>)}{!state.tasks.length&&<Empty text="No next actions yet. Add one in the action view."/>}</section><section><div className="section-title"><h2>Begin with sources</h2></div><div className="choice-grid"><button onClick={()=>doImport('copy')}><Upload/><strong>Managed copy</strong><span>Portable: the original is copied into this workspace.</span></button><button onClick={()=>doImport('link')}><FolderOpen/><strong>Linked file</strong><span>Space-saving: depends on the file staying in its current location.</span></button></div></section></div>}
function Metric({n,text}:{n:number;text:string}){return <div className="metric"><strong>{n}</strong><span>{text}</span></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}

function DocumentView({tab,state,refresh,openCompare}:{tab:Tab;state:AppState;refresh:()=>void;openCompare:(x:string)=>void}){if(tab.kind==='compare'&&tab.compareId)return <Compare left={tab.itemId} right={tab.compareId}/>;const item=state.items.find(x=>x.id===tab.itemId);const [data,setData]=useState<any>(),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[find,setFind]=useState(''),[selection,setSelection]=useState(''),[showEvidence,setShowEvidence]=useState(false),[compare,setCompare]=useState('');useEffect(()=>{setData(undefined);window.researchDesk.readItem(tab.itemId).then(setData).catch(e=>setData({error:e.message}));},[tab.itemId]);if(!item)return <Empty text="This item no longer exists."/>;if(data?.error)return <div className="document-error"><h2>Source unavailable</h2><p>{data.error}</p>{item.storageMode==='link'&&<button className="primary" onClick={async()=>{const x=await window.researchDesk.relinkItem(item.id);if(x){refresh();setData(await window.researchDesk.readItem(item.id));}}}>Relink matching file</button>}</div>;
  const capture=()=>{const text=window.getSelection()?.toString().trim();if(text)setSelection(text);};
  return <div className="document-shell"><div className="document-toolbar"><span className="doc-type">{item.mediaType.split('/').pop()?.toUpperCase()}</span><strong>{item.title}</strong><span className="doc-meta">{item.storageMode==='copy'?'Managed copy':'Linked original'}</span><div className="spacer"/><div className="find"><Search size={14}/><input value={find} onChange={e=>setFind(e.target.value)} placeholder="Find in document"/></div><button onClick={()=>setZoom(z=>Math.max(.5,z-.15))}><ZoomOut size={16}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(3,z+.15))}><ZoomIn size={16}/></button>{item.mediaType.startsWith('image/')&&<button onClick={()=>setRotation(x=>(x+90)%360)} title="Rotate view only"><RotateCw size={16}/></button>}<select value={compare} onChange={e=>{setCompare(e.target.value);if(e.target.value)openCompare(e.target.value)}} aria-label="Compare with"><option value="">Compare…</option>{state.items.filter(x=>x.id!==item.id).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button onClick={()=>window.researchDesk.revealItem(item.id)}><MoreHorizontal size={16}/></button></div>
    {selection&&<div className="selection-bar"><span>“{selection.slice(0,90)}{selection.length>90?'…':''}”</span><button className="primary small" onClick={()=>setShowEvidence(true)}>Attach to evidence</button><button onClick={()=>setSelection('')}>Clear</button></div>}
    <div className="document-stage" onMouseUp={capture}>{!data?<div className="loading">Opening source…</div>:item.mediaType==='application/pdf'?<embed className="pdf" src={`${data.url}#zoom=${Math.round(zoom*100)}`} type="application/pdf"/>:item.mediaType.startsWith('image/')?<div className="image-canvas"><img src={data.url} style={{transform:`scale(${zoom}) rotate(${rotation}deg)`}} alt={item.title}/><span className="non-destructive">Rotation is view-only; the original is unchanged.</span></div>:item.mediaType.includes('wordprocessingml')?<div className="prose"><div className="warning">DOCX is rendered for reading and may differ from Microsoft Word. The original remains intact. <button onClick={()=>window.researchDesk.openInSystem(item.id)}>Open in system editor</button></div><div dangerouslySetInnerHTML={{__html:highlight(data.html||'',find)}}/></div>:<TextEditor item={item} initial={data.text||''} zoom={zoom} find={find}/>}</div>
    {showEvidence&&<EvidenceModal item={item} quote={selection} onClose={()=>setShowEvidence(false)} onSaved={()=>{setShowEvidence(false);setSelection('');refresh();}}/>}
  </div>}
function highlight(html:string,find:string){if(!find)return html;const escaped=find.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return html.replace(new RegExp(`(${escaped})`,'gi'),'<mark>$1</mark>')}
function TextEditor({item,initial,zoom,find}:{item:LibraryItem;initial:string;zoom:number;find:string}){const [text,setText]=useState(initial),[saved,setSaved]=useState(true);useEffect(()=>setText(initial),[initial]);return <div className="text-editor" style={{fontSize:`${zoom}rem`}}><div className="editor-note">Editable {item.mediaType==='text/markdown'?'Markdown':'plain text'} · original updates only when you save</div>{find&&<div className="find-count">{text.toLowerCase().split(find.toLowerCase()).length-1} matches</div>}<textarea value={text} onChange={e=>{setText(e.target.value);setSaved(false)}} spellCheck/><button className="primary save" disabled={saved} onClick={async()=>{await window.researchDesk.saveText(item.id,text);setSaved(true)}}>{saved?'Saved':'Save changes'}</button></div>}
function EvidenceModal({item,quote,onClose,onSaved}:{item:LibraryItem;quote:string;onClose:()=>void;onSaved:()=>void}){const [title,setTitle]=useState(`Passage from ${item.title}`),[locator,setLocator]=useState(''),[interpretation,setInterpretation]=useState(''),[limitations,setLimitations]=useState('');return <div className="modal-backdrop"><form className="modal" onSubmit={async e=>{e.preventDefault();await window.researchDesk.createEvidence({sourceId:item.id,title,locator,quotation:quote,interpretation,limitations,verificationStatus:'machine-extracted'});onSaved();}}><p className="eyebrow">NEW EVIDENCE RECORD</p><h2>Keep the passage connected</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Precise locator<input value={locator} onChange={e=>setLocator(e.target.value)} placeholder="Page, section, paragraph, or image region" required/></label><label>Quotation<textarea value={quote} readOnly/></label><label>Interpretation<textarea value={interpretation} onChange={e=>setInterpretation(e.target.value)}/></label><label>Limitations<textarea value={limitations} onChange={e=>setLimitations(e.target.value)}/></label><p className="fineprint">Saved as machine-extracted until a person marks it visually checked.</p><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary">Create evidence</button></div></form></div>}
function Compare({left,right}:{left:string;right:string}){return <div className="compare"><MiniDocument id={left}/><MiniDocument id={right}/></div>}
function MiniDocument({id}:{id:string}){const [data,setData]=useState<any>();useEffect(()=>{window.researchDesk.readItem(id).then(setData).catch(e=>setData({error:e.message}))},[id]);if(!data)return <div className="loading">Opening…</div>;if(data.error)return <div className="document-error">{data.error}</div>;return <div className="mini-doc"><h3>{data.item.title}</h3>{data.url?(data.item.mediaType.startsWith('image/')?<img src={data.url}/>:<embed src={data.url} type={data.item.mediaType}/>):data.html?<div className="prose" dangerouslySetInnerHTML={{__html:data.html}}/>:<pre>{data.text}</pre>}</div>}

function NavView({view,state,refresh,openItem}:{view:View;state:AppState;refresh:()=>void;openItem:(x:LibraryItem)=>void}){
  if(view==='actions')return <Actions state={state} refresh={refresh}/>;
  if(view==='arguments')return <Arguments state={state} refresh={refresh}/>;
  if(view==='inbox')return <div className="panel-list"><button className="primary full" disabled={!state.items.length} onClick={async()=>{const sourceId=state.items[0]?.id;if(sourceId){await window.researchDesk.createEvidence({sourceId,title:'New evidence record'});refresh();}}}><Plus size={15}/>New evidence</button>{state.evidence.map(e=><article className="record-card" key={e.id}><span className="tag">{e.verificationStatus}</span><h3>{e.title}</h3><p>{e.quotation||'No quotation recorded.'}</p><small>{e.locator||'Locator missing'}</small>{state.items.find(x=>x.id===e.sourceId)&&<button className="link" onClick={()=>openItem(state.items.find(x=>x.id===e.sourceId)!)}>Open source →</button>}</article>)}{!state.evidence.length&&<Empty text="Select text in a source to create your first evidence record."/>}</div>;
  if(view==='checks')return <div className="panel-list">{state.checks.map(c=><article className="check-card" key={c.id}><span className={`status-dot ${c.severity}`}/><div><h3>{c.title}</h3><p>{c.detail}</p></div></article>)}{!state.checks.length&&<div className="all-clear"><CheckCircle2/><strong>No current workflow issues</strong><span>Checks update as records change.</span></div>}</div>;
  if(view==='revisions')return <div className="panel-list"><div className="callout"><strong>Review before applying</strong><p>Revision proposals should point to a document version and stable text anchor. Original DOCX files are never rewritten here.</p></div><Empty text="No revision proposals. This release exports suggestions; it does not replace Word."/></div>;
  return <SettingsPane state={state} refresh={refresh}/>;
}
function Actions({state,refresh}:{state:AppState;refresh:()=>void}){const move=async(index:number,delta:number)=>{const ids=state.tasks.map(x=>x.id),target=index+delta;if(target<0||target>=ids.length)return;[ids[index],ids[target]]=[ids[target],ids[index]];await window.researchDesk.reorderTasks(ids);refresh()};return <div className="panel-list"><button className="primary full" onClick={async()=>{await window.researchDesk.createTask({title:'New next action',status:'ready'});refresh();}}><Plus size={15}/>Add action</button>{state.tasks.slice(0,3).map((t,i)=><article className="action-card" key={t.id}><span className="ordinal">0{i+1}<button aria-label="Move action up" disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button aria-label="Move action down" disabled={i===state.tasks.length-1} onClick={()=>move(i,1)}>↓</button></span><div><h3>{t.title}</h3><label>Why it matters<p>{t.why||'Not recorded'}</p></label><label>Could change<p>{t.impact||'Not recorded'}</p></label><label>Available sources<p>{t.sources||'None listed'}</p></label><label>Blocker<p>{t.blocker||'None'}</p></label><label>Done when<p>{t.completion||'Add a completion criterion'}</p></label><span className={`tag ${t.status}`}>{t.status}</span></div></article>)}{!state.tasks.length&&<Empty text="Create up to three concrete actions. Broad projects belong in notes, not this queue."/>}</div>}
function Arguments({state,refresh}:{state:AppState;refresh:()=>void}){const [selected,setSelected]=useState(state.claims[0]?.id),[wording,setWording]=useState('');const claim=state.claims.find(x=>x.id===selected);const links=state.claimLinks.filter(x=>x.claimId===selected);return <div className="arguments"><button className="primary full" onClick={async()=>{const x=await window.researchDesk.createClaim({wording:wording||'New claim'});setWording('');await refresh();setSelected(x.claims[0]?.id)}}><Plus size={15}/>New claim</button><input value={wording} onChange={e=>setWording(e.target.value)} placeholder="Draft claim wording"/>{state.claims.map(c=><button className={`claim-row ${selected===c.id?'active':''}`} key={c.id} onClick={()=>setSelected(c.id)}>{c.wording}</button>)}{claim&&<div className="claim-detail"><p className="eyebrow">CURRENT WORDING</p><h3>{claim.wording}</h3><span className="tag">{claim.assessment}</span><h4>Reasoning</h4><p>{claim.reasoning||'Not yet recorded.'}</p><h4>Remaining uncertainties</h4><p>{claim.uncertainties||'Not yet recorded.'}</p><h4>Relevant manuscript section</h4><p>{claim.manuscriptLocation||'None linked.'}</p>{(['supports','qualifies','contradicts','context'] as ClaimLink['relationship'][]).map(kind=><div key={kind}><h4>{kind[0].toUpperCase()+kind.slice(1)}</h4>{links.filter(x=>x.relationship===kind).map(l=><p key={l.id}>{state.evidence.find(e=>e.id===l.evidenceId)?.title}</p>)}{!links.some(x=>x.relationship===kind)&&<p className="muted">None linked.</p>}</div>)}{state.evidence.length>0&&<button onClick={async()=>{await window.researchDesk.linkEvidence(claim.id,state.evidence[0].id,'supports');refresh();}}>Link first evidence as support</button>}</div>}</div>}
function SettingsPane({state,refresh}:{state:AppState;refresh:()=>void}){
  const emptyAi:AiSettings={configured:false,model:'gpt-5-mini',provider:null,chatGptConnected:false};
  const emptyChatGpt:ChatGptConnectionStatus={connected:false,models:[],selectedModel:''};
  const [ai,setAi]=useState<AiSettings>(emptyAi),[chatGpt,setChatGpt]=useState<ChatGptConnectionStatus>(emptyChatGpt),[key,setKey]=useState(''),[model,setModel]=useState('gpt-5-mini'),[brand,setBrand]=useState(defaultBrand),[message,setMessage]=useState(''),[connecting,setConnecting]=useState(false);
  const reloadAi=async()=>{const [nextAi,nextChatGpt]=await Promise.all([window.researchDesk.getAiSettings(),window.researchDesk.getChatGptStatus()]);setAi(nextAi);setChatGpt(nextChatGpt);if(nextAi.provider==='api-key')setModel(nextAi.model)};
  useEffect(()=>{void reloadAi();window.researchDesk.getBrand().then(setBrand)},[]);
  const connect=async()=>{setConnecting(true);setMessage('Your browser is opening. Sign in there, then return to Research Desk.');try{setChatGpt(await window.researchDesk.connectChatGpt());await reloadAi();setMessage('Your personal ChatGPT account is connected.');}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setConnecting(false)}};
  const disconnect=async()=>{setConnecting(true);try{const result=await window.researchDesk.disconnectChatGpt();setChatGpt(result);await reloadAi();setMessage(result.warning||'ChatGPT was disconnected from this computer.');}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setConnecting(false)}};
  return <div className="settings-pane">
    <section><p className="eyebrow">WORKSPACE</p><h3>{state.workspace?.name}</h3><button onClick={async()=>{const name=prompt('New workspace name',state.workspace?.name);if(name){await window.researchDesk.renameWorkspace(name);refresh();}}}>Rename</button><button onClick={async()=>{const file=await window.researchDesk.exportWorkspace();if(file)setMessage(`Exported to ${file}`)}}>Export portable archive</button><button onClick={async()=>{await window.researchDesk.closeWorkspace();refresh()}}>Close workspace</button><p className="fineprint">Exports include managed source files and the database, with SHA-256 integrity checks. Credentials are excluded.</p></section>
    <section className="chatgpt-account"><p className="eyebrow">PERSONAL CHATGPT</p><span className={`connection ${chatGpt.connected?'ok':''}`}>{chatGpt.connected?'Connected':'Not connected'}</span>{chatGpt.connected?<><h3>{chatGpt.name||chatGpt.email||'ChatGPT account'}</h3>{chatGpt.name&&chatGpt.email&&<p className="fineprint">{chatGpt.email}</p>}<label>ChatGPT model<select value={chatGpt.selectedModel} onChange={async e=>{setChatGpt(await window.researchDesk.setChatGptModel(e.target.value));await reloadAi();}}>{chatGpt.models.map(item=><option key={item.slug} value={item.slug}>{item.displayName}</option>)}</select></label><button disabled={connecting} onClick={async()=>{setChatGpt(await window.researchDesk.refreshChatGptModels());setMessage('Model list refreshed.')}}>Refresh models</button><button disabled={connecting} onClick={disconnect}>Disconnect</button><button onClick={()=>window.researchDesk.openExternal('https://chatgpt.com')}>Open ChatGPT ↗</button></>:<><h3>Use your ChatGPT plan</h3><p>Sign in through OpenAI in your browser. Research Desk never sees your password. Your scoped session is encrypted by Windows and excluded from workspace exports.</p><button className="primary full" disabled={connecting} onClick={connect}>{connecting?'Waiting for browser…':'Continue with ChatGPT'}</button></>}<p className="fineprint">This connection can run supported models against context you choose to send. It cannot read your ChatGPT chats, memory, files, or custom GPTs. Availability and usage limits depend on your plan.</p></section>
    <section><p className="eyebrow">WHITE LABEL</p><label>Application name<input value={brand.appName} onChange={e=>setBrand({...brand,appName:e.target.value})}/></label><label>Accent color<input type="color" value={brand.accent} onChange={e=>setBrand({...brand,accent:e.target.value})}/></label><button onClick={async()=>{setBrand(await window.researchDesk.setBrand(brand));location.reload()}}>Save branding</button></section>
    <section><p className="eyebrow">OPENAI API KEY (ALTERNATIVE)</p><span className={`connection ${ai.provider==='api-key'?'ok':''}`}>{ai.provider==='api-key'?'Active':'Optional'}</span><label>API key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-…"/></label><label>Model<input value={model} onChange={e=>setModel(e.target.value)} list="models"/><datalist id="models"><option value="gpt-5-mini"/><option value="gpt-5"/><option value="gpt-4.1"/></datalist></label><button disabled={!key} onClick={async()=>{const next=await window.researchDesk.saveAiSettings(key,model);setAi(next);setKey('');setMessage('The API key is now the active provider and is protected by operating-system encryption.')}}>Save and use API key</button><p className="fineprint">API billing is separate from ChatGPT. Saving a key switches the assistant to that API project; choosing a ChatGPT model switches it back.</p></section>
    <section><p className="eyebrow">GOOGLE DRIVE</p><span className="connection">Setup required</span><p>Drive import is not enabled in this release. A distributable app needs its own Google Cloud OAuth client and consent configuration. Use the narrow <code>drive.file</code> scope with a user picker; never paste a client secret here.</p><button onClick={()=>window.researchDesk.openExternal('https://developers.google.com/workspace/drive/api/guides/api-specific-auth')}>Official setup guide ↗</button></section><section><p className="eyebrow">AIRTABLE CATALOGUE</p><span className="connection">Setup required</span><p>Catalogue import and field mapping are not enabled in this release. Use a user-created, base-scoped personal access token for read-only snapshots. API keys are obsolete.</p><button onClick={()=>window.researchDesk.openExternal('https://support.airtable.com/docs/creating-personal-access-tokens')}>Official token guide ↗</button></section>{message&&<div className="callout">{message}</div>}
  </div>
}

function friendlyAiError(value:unknown){const raw=value instanceof Error?value.message:String(value);if(raw.includes('Subscription Sharing usage limit')||raw.includes('subscription_sharing_usage_limit_exceeded'))return 'ChatGPT usage limit reached. Review ChatGPT Settings → Usage, wait for the applicable limit to reset, or switch to an API key.';return raw.replace(/^Error invoking remote method 'chat:send': Error: /,'')}

function AssistantWithModelPicker({state,currentItemId}:{state:AppState;currentItemId?:string}){
  const [settings,setSettings]=useState<AiSettings>({configured:false,model:'',provider:null,chatGptConnected:false});
  const [chatGpt,setChatGpt]=useState<ChatGptConnectionStatus>({connected:false,models:[],selectedModel:''});
  const [text,setText]=useState(''),[attached,setAttached]=useState<string[]>([]),[messages,setMessages]=useState<{role:string;content:string}[]>([]),[conversationId,setConversationId]=useState<string>(),[stream,setStream]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[changingModel,setChangingModel]=useState(false);
  const loadProvider=async()=>{const [nextSettings,nextChatGpt]=await Promise.all([window.researchDesk.getAiSettings(),window.researchDesk.getChatGptStatus()]);setSettings(nextSettings);setChatGpt(nextChatGpt)};
  useEffect(()=>{void loadProvider()},[]);
  useEffect(()=>window.researchDesk.onChatChunk(event=>{if(event.conversationId===conversationId){setStream(value=>value+event.delta);if(event.error)setError(friendlyAiError(event.error));if(event.done)setBusy(false)}}),[conversationId]);
  const changeModel=async(model:string)=>{setChangingModel(true);setError('');try{if(settings.provider==='chatgpt')setChatGpt(await window.researchDesk.setChatGptModel(model));else await window.researchDesk.saveAiSettings('',model);await loadProvider()}catch(reason){setError(friendlyAiError(reason))}finally{setChangingModel(false)}};
  const refreshModels=async()=>{setChangingModel(true);setError('');try{setChatGpt(await window.researchDesk.refreshChatGptModels());await loadProvider()}catch(reason){setError(friendlyAiError(reason))}finally{setChangingModel(false)}};
  const send=async()=>{if(!text.trim())return;const prompt=text;const id=conversationId||crypto.randomUUID();setConversationId(id);setText('');setMessages(value=>[...value,{role:'user',content:prompt}]);setStream('');setError('');setBusy(true);try{const result=await window.researchDesk.chat({conversationId:id,message:prompt,itemId:currentItemId,evidenceIds:attached});setMessages(value=>[...value,{role:'assistant',content:result.message.content}]);setStream('')}catch(reason){setError(friendlyAiError(reason));setBusy(false)}};
  const apiModels=Array.from(new Set([settings.model,'gpt-5-mini','gpt-5','gpt-4.1'].filter(Boolean)));
  return <div className="assistant">
    <div className="side-heading"><span>Research assistant</span><Bot size={17}/></div>
    {settings.configured&&<div className="provider-strip model-picker"><span>{settings.provider==='chatgpt'?'Using ChatGPT plan':'Using OpenAI API'}</span><select aria-label="Assistant model" value={settings.model} disabled={busy||changingModel} onChange={event=>void changeModel(event.target.value)}>{settings.provider==='chatgpt'?chatGpt.models.map(model=><option key={model.slug} value={model.slug}>{model.displayName}</option>):apiModels.map(model=><option key={model} value={model}>{model}</option>)}</select>{settings.provider==='chatgpt'&&<button aria-label="Refresh available models" title="Refresh available models" disabled={busy||changingModel} onClick={()=>void refreshModels()}><RotateCw size={13}/></button>}</div>}
    {!settings.configured&&<div className="setup-state"><Bot size={30}/><h3>Connect an AI provider</h3><p>No live provider is configured. Research Desk will not simulate an answer.</p><small>Open Settings → Personal ChatGPT, or add an API key.</small></div>}
    <div className="context"><p className="eyebrow">CONTEXT YOU CONTROL</p>{currentItemId&&<span className="chip"><File size={12}/>{state.items.find(item=>item.id===currentItemId)?.title}</span>}{attached.map(id=><span className="chip" key={id}>{state.evidence.find(item=>item.id===id)?.title}<button onClick={()=>setAttached(value=>value.filter(item=>item!==id))}>×</button></span>)}<select value="" onChange={event=>setAttached(value=>value.includes(event.target.value)?value:[...value,event.target.value])}><option value="">Attach evidence…</option>{state.evidence.filter(item=>!attached.includes(item.id)).map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select><p className="fineprint">Retrieved materials are shown here before sending. Source text is treated as evidence, not instructions.</p></div>
    <div className="messages">{messages.map((message,index)=><div className={`message ${message.role}`} key={index}><strong>{message.role==='user'?'You':'Assistant'}</strong><p>{message.content}</p></div>)}{stream&&<div className="message assistant"><strong>Assistant</strong><p>{stream}</p></div>}{error&&<div className="error-message">{error}</div>}</div>
    <div className="composer"><textarea value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey))void send()}} placeholder={settings.configured?'Ask about the attached material…':'Connect ChatGPT or configure an API key'} disabled={!settings.configured}/><div><span>Ctrl ↵ to send</span>{busy?<button onClick={()=>conversationId&&window.researchDesk.cancelChat(conversationId)}>Cancel</button>:<button className="primary" disabled={!settings.configured||!text.trim()} onClick={send}><MessageSquare size={15}/>Send</button>}</div></div>
  </div>
}
function Resizer({side,onMove}:{side:'left'|'right';onMove:(d:number)=>void}){const start=useRef(0);return <div className={`resizer ${side}`} onMouseDown={e=>{start.current=e.clientX;const move=(x:MouseEvent)=>{onMove(x.clientX-start.current);start.current=x.clientX};const up=()=>{removeEventListener('mousemove',move);removeEventListener('mouseup',up)};addEventListener('mousemove',move);addEventListener('mouseup',up)}}/>}
